# vim:ft=ansible:
---
- hosts: rpies
  vars:
    pkgs: [ 'apt-transport-https', 'ca-certificates', 'curl', 'docker.io', 'gnupg2', 'htop', 'mc' ]
  tasks:
    - name: Install packages
      apt: pkg={{ pkgs }} state=latest update_cache=true
